version = 1

exclude_patterns = [
   "vendor/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/siddhant-deepsource/test-sym"
  dependencies_vendored = true
